<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [   'id'=>1,
                'brands_id'=>"1",
                'name'=>'',
                'price'=>"",
                'content'=>"",
                'color'=>"",
                'image'=>"",
                'size'=>"",
                'sex'=>"",
                'quantity'=>""],
            [   'id'=>2,
                'brands_id'=>"1",
                'name'=>'',
                'price'=>"",
                'content'=>"",
                'color'=>"",
                'image'=>"",
                'size'=>"",
                'sex'=>"",
                'quantity'=>""],
            [   'id'=>3,
                'brands_id'=>"2",
                'name'=>'',
                'price'=>"",
                'content'=>"",
                'color'=>"",
                'image'=>"",
                'size'=>"",
                'sex'=>"",
                'quantity'=>""],
            [   'id'=>4,
                'brands_id'=>"2",
                'name'=>'',
                'price'=>"",
                'content'=>"",
                'color'=>"",
                'image'=>"",
                'size'=>"",
                'sex'=>"",
                'quantity'=>""],
            [   'id'=>5,
                'brands_id'=>"3",
                'name'=>'',
                'price'=>"",
                'content'=>"",
                'color'=>"",
                'image'=>"",
                'size'=>"",
                'sex'=>"",
                'quantity'=>""],
            [   'id'=>6,
                'brands_id'=>"3",
                'name'=>'',
                'price'=>"",
                'content'=>"",
                'color'=>"",
                'image'=>"",
                'size'=>"",
                'sex'=>"",
                'quantity'=>""],
            [   'id'=>7,
                'brands_id'=>"4",
                'name'=>'',
                'price'=>"",
                'content'=>"",
                'color'=>"",
                'image'=>"",
                'size'=>"",
                'sex'=>"",
                'quantity'=>""],
            [   'id'=>8,
                'brands_id'=>"4",
                'name'=>'',
                'price'=>"",
                'content'=>"",
                'color'=>"",
                'image'=>"",
                'size'=>"",
                'sex'=>"",
                'quantity'=>""],
            [   'id'=>9,
                'brands_id'=>"5",
                'name'=>'',
                'price'=>"",
                'content'=>"",
                'color'=>"",
                'image'=>"",
                'size'=>"",
                'sex'=>"",
                'quantity'=>""],
            [   'id'=>10,
                'brands_id'=>"5",
                'name'=>'',
                'price'=>"",
                'content'=>"",
                'color'=>"",
                'image'=>"",
                'size'=>"",
                'sex'=>"",
                'quantity'=>""],
            [   'id'=>11,
                'brands_id'=>"6",
                'name'=>'',
                'price'=>"",
                'content'=>"",
                'color'=>"",
                'image'=>"",
                'size'=>"",
                'sex'=>"",
                'quantity'=>""],
            [   'id'=>12,
                'brands_id'=>"6",
                'name'=>'',
                'price'=>"",
                'content'=>"",
                'color'=>"",
                'image'=>"",
                'size'=>"",
                'sex'=>"",
                'quantity'=>""]
        ]);
    }
}
